### ISSUE TITLE
Editor

### ISSUE THREAD

**Issue by Lewismjones92** [JonBetts/CM0102-Starter-Kit#1]
Can i edit a player once ive started a saved game? I can edit players before i create a new game but then once im playing the edits that im doing arnt registering on my saved game ?
Any help would be great
Thanks

**Comment by JonBetts** [comment]
You need a save game editor for that. The official editor doesn't support that.

**Comment by Lewismjones92** [comment]
Can i get that whilst in the save that im already into now ?

**Comment by JonBetts** [comment]
Yes just download one.

**Comment by Lewismjones92** [comment]
Im not that clued up with how to use  it all, do you have a link ?

**Comment by JonBetts** [comment]
Go to www.champman0102.net.
